// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(dataline_ffiFFI)
import dataline_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_dataline_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_dataline_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }

    init(rawBufferPointer: UnsafeRawBufferPointer) {
        self.init(
            len: Int32(rawBufferPointer.count),
            data: rawBufferPointer.baseAddress?.assumingMemoryBound(to: UInt8.self)
        )
    }
}

// Converter for `&[u8]` / `[ByRef] bytes` arguments.
//
// Conforms to `FfiConverter` so the compiler enforces the full converter
// method set. Only the scope-bound `lower(_:_body:)` overload is sound —
// zero-copy byte buffers only flow foreign -> Rust, and only in argument
// position. The four protocol-witness methods (`lift`, `lower`, `read`,
// `write`) `fatalError` at runtime if anyone reaches them.
//
// The scope-bound `lower` takes a closure because the `ForeignBytes`
// pointer is only guaranteed valid for the duration of
// `Data.withUnsafeBytes`. Callers must run the full FFI call inside
// the closure body.
fileprivate enum FfiConverterByRefBytes: FfiConverter {
    typealias SwiftType = Data
    typealias FfiType = ForeignBytes

    static func lower<R>(_ value: Data, _ body: (ForeignBytes) throws -> R) rethrows -> R {
        return try value.withUnsafeBytes { rawBuf in
            try body(ForeignBytes(rawBufferPointer: rawBuf))
        }
    }

    static func lower(_ value: Data) -> ForeignBytes {
        fatalError("ByRef bytes cannot use the plain lower: returning ForeignBytes escapes the Data.withUnsafeBytes scope. Use the scope-bound lower(_:_body:) overload instead.")
    }

    static func lift(_ value: ForeignBytes) throws -> Data {
        fatalError("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        fatalError("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }

    static func write(_ value: Data, into buf: inout [UInt8]) {
        fatalError("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureDatalineFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt32: FfiConverterPrimitive {
    typealias FfiType = Int32
    typealias SwiftType = Int32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int32, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        // Use Swift's native UTF-8 decoder; `String(bytes:encoding:.utf8)` goes
        // through Foundation's NSString and silently strips a leading U+FEFF BOM.
        // Invalid UTF-8 substitutes U+FFFD instead of trapping (unreachable
        // given Rust's `String` invariant).
        return String(decoding: bytes, as: UTF8.self)
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        // See `lift` above for why we avoid Foundation's NSString-backed decoder here.
        return String(decoding: try readBytes(&buf, count: Int(len)), as: UTF8.self)
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




public protocol StoreProtocol: AnyObject, Sendable {
    
    func addField(databaseId: String, name: String, kind: FieldKind) throws  -> String
    
    func createDatabase(name: String) throws  -> String
    
    func createRecord(databaseId: String) throws  -> String
    
    func createReference(sourceLink: String, sourceField: String, targetLink: String) throws  -> Reference
    
    func deleteRecord(link: String) throws 
    
    func deleteReference(referenceId: String, field: String) throws 
    
    func duplicateDatabaseSchema(databaseId: String, newName: String) throws  -> String
    
    func findByValue(databaseId: String, fieldId: String, value: Value) throws  -> [Record]
    
    func getDatabase(databaseId: String) throws  -> Database
    
    func getRecord(link: String) throws  -> Record
    
    func listDatabases()  -> [Database]
    
    func listRecords(databaseId: String) throws  -> [Record]
    
    func listReferences(link: String, field: String) throws  -> [Reference]
    
    func readBlob(hash: String) throws  -> Data
    
    func relatedRecords(link: String) throws  -> [String]
    
    func removeField(databaseId: String, fieldId: String) throws 
    
    func renameField(databaseId: String, fieldId: String, name: String) throws 
    
    func retypeField(databaseId: String, fieldId: String, kind: FieldKind) throws  -> RetypeReport
    
    func searchText(databaseId: String, query: String) throws  -> [Record]
    
    func setValue(link: String, fieldId: String, value: Value) throws 
    
    func writeBlob(bytes: Data) throws  -> String
    
}
open class Store: StoreProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_dataline_ffi_fn_clone_store(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_dataline_ffi_fn_free_store(handle, $0) }
    }

    
public static func `open`(path: String)throws  -> Store  {
    return try  FfiConverterTypeStore_lift(try rustCallWithError(FfiConverterTypeDataLineError_lift) {
        uniffiCallStatus in
    uniffi_dataline_ffi_fn_constructor_store_open(
        FfiConverterString.lower(path),uniffiCallStatus
    )
})
}
    

    
open func addField(databaseId: String, name: String, kind: FieldKind)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeDataLineError_lift) {
        uniffiCallStatus in
    uniffi_dataline_ffi_fn_method_store_add_field(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(databaseId),
        FfiConverterString.lower(name),
        FfiConverterTypeFieldKind_lower(kind),uniffiCallStatus
    )
})
}
    
open func createDatabase(name: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeDataLineError_lift) {
        uniffiCallStatus in
    uniffi_dataline_ffi_fn_method_store_create_database(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(name),uniffiCallStatus
    )
})
}
    
open func createRecord(databaseId: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeDataLineError_lift) {
        uniffiCallStatus in
    uniffi_dataline_ffi_fn_method_store_create_record(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(databaseId),uniffiCallStatus
    )
})
}
    
open func createReference(sourceLink: String, sourceField: String, targetLink: String)throws  -> Reference  {
    return try  FfiConverterTypeReference_lift(try rustCallWithError(FfiConverterTypeDataLineError_lift) {
        uniffiCallStatus in
    uniffi_dataline_ffi_fn_method_store_create_reference(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(sourceLink),
        FfiConverterString.lower(sourceField),
        FfiConverterString.lower(targetLink),uniffiCallStatus
    )
})
}
    
open func deleteRecord(link: String)throws   {try rustCallWithError(FfiConverterTypeDataLineError_lift) {
        uniffiCallStatus in
    uniffi_dataline_ffi_fn_method_store_delete_record(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(link),uniffiCallStatus
    )
}
}
    
open func deleteReference(referenceId: String, field: String)throws   {try rustCallWithError(FfiConverterTypeDataLineError_lift) {
        uniffiCallStatus in
    uniffi_dataline_ffi_fn_method_store_delete_reference(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(referenceId),
        FfiConverterString.lower(field),uniffiCallStatus
    )
}
}
    
open func duplicateDatabaseSchema(databaseId: String, newName: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeDataLineError_lift) {
        uniffiCallStatus in
    uniffi_dataline_ffi_fn_method_store_duplicate_database_schema(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(databaseId),
        FfiConverterString.lower(newName),uniffiCallStatus
    )
})
}
    
open func findByValue(databaseId: String, fieldId: String, value: Value)throws  -> [Record]  {
    return try  FfiConverterSequenceTypeRecord.lift(try rustCallWithError(FfiConverterTypeDataLineError_lift) {
        uniffiCallStatus in
    uniffi_dataline_ffi_fn_method_store_find_by_value(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(databaseId),
        FfiConverterString.lower(fieldId),
        FfiConverterTypeValue_lower(value),uniffiCallStatus
    )
})
}
    
open func getDatabase(databaseId: String)throws  -> Database  {
    return try  FfiConverterTypeDatabase_lift(try rustCallWithError(FfiConverterTypeDataLineError_lift) {
        uniffiCallStatus in
    uniffi_dataline_ffi_fn_method_store_get_database(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(databaseId),uniffiCallStatus
    )
})
}
    
open func getRecord(link: String)throws  -> Record  {
    return try  FfiConverterTypeRecord_lift(try rustCallWithError(FfiConverterTypeDataLineError_lift) {
        uniffiCallStatus in
    uniffi_dataline_ffi_fn_method_store_get_record(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(link),uniffiCallStatus
    )
})
}
    
open func listDatabases() -> [Database]  {
    return try!  FfiConverterSequenceTypeDatabase.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_dataline_ffi_fn_method_store_list_databases(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
open func listRecords(databaseId: String)throws  -> [Record]  {
    return try  FfiConverterSequenceTypeRecord.lift(try rustCallWithError(FfiConverterTypeDataLineError_lift) {
        uniffiCallStatus in
    uniffi_dataline_ffi_fn_method_store_list_records(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(databaseId),uniffiCallStatus
    )
})
}
    
open func listReferences(link: String, field: String)throws  -> [Reference]  {
    return try  FfiConverterSequenceTypeReference.lift(try rustCallWithError(FfiConverterTypeDataLineError_lift) {
        uniffiCallStatus in
    uniffi_dataline_ffi_fn_method_store_list_references(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(link),
        FfiConverterString.lower(field),uniffiCallStatus
    )
})
}
    
open func readBlob(hash: String)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeDataLineError_lift) {
        uniffiCallStatus in
    uniffi_dataline_ffi_fn_method_store_read_blob(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(hash),uniffiCallStatus
    )
})
}
    
open func relatedRecords(link: String)throws  -> [String]  {
    return try  FfiConverterSequenceString.lift(try rustCallWithError(FfiConverterTypeDataLineError_lift) {
        uniffiCallStatus in
    uniffi_dataline_ffi_fn_method_store_related_records(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(link),uniffiCallStatus
    )
})
}
    
open func removeField(databaseId: String, fieldId: String)throws   {try rustCallWithError(FfiConverterTypeDataLineError_lift) {
        uniffiCallStatus in
    uniffi_dataline_ffi_fn_method_store_remove_field(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(databaseId),
        FfiConverterString.lower(fieldId),uniffiCallStatus
    )
}
}
    
open func renameField(databaseId: String, fieldId: String, name: String)throws   {try rustCallWithError(FfiConverterTypeDataLineError_lift) {
        uniffiCallStatus in
    uniffi_dataline_ffi_fn_method_store_rename_field(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(databaseId),
        FfiConverterString.lower(fieldId),
        FfiConverterString.lower(name),uniffiCallStatus
    )
}
}
    
open func retypeField(databaseId: String, fieldId: String, kind: FieldKind)throws  -> RetypeReport  {
    return try  FfiConverterTypeRetypeReport_lift(try rustCallWithError(FfiConverterTypeDataLineError_lift) {
        uniffiCallStatus in
    uniffi_dataline_ffi_fn_method_store_retype_field(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(databaseId),
        FfiConverterString.lower(fieldId),
        FfiConverterTypeFieldKind_lower(kind),uniffiCallStatus
    )
})
}
    
open func searchText(databaseId: String, query: String)throws  -> [Record]  {
    return try  FfiConverterSequenceTypeRecord.lift(try rustCallWithError(FfiConverterTypeDataLineError_lift) {
        uniffiCallStatus in
    uniffi_dataline_ffi_fn_method_store_search_text(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(databaseId),
        FfiConverterString.lower(query),uniffiCallStatus
    )
})
}
    
open func setValue(link: String, fieldId: String, value: Value)throws   {try rustCallWithError(FfiConverterTypeDataLineError_lift) {
        uniffiCallStatus in
    uniffi_dataline_ffi_fn_method_store_set_value(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(link),
        FfiConverterString.lower(fieldId),
        FfiConverterTypeValue_lower(value),uniffiCallStatus
    )
}
}
    
open func writeBlob(bytes: Data)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeDataLineError_lift) {
        uniffiCallStatus in
    uniffi_dataline_ffi_fn_method_store_write_blob(
            self.uniffiCloneHandle(),
        FfiConverterData.lower(bytes),uniffiCallStatus
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeStore: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = Store

    public static func lift(_ handle: UInt64) throws -> Store {
        return Store(unsafeFromHandle: handle)
    }

    public static func lower(_ value: Store) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Store {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: Store, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStore_lift(_ handle: UInt64) throws -> Store {
    return try FfiConverterTypeStore.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStore_lower(_ value: Store) -> UInt64 {
    return FfiConverterTypeStore.lower(value)
}




public struct Database: Equatable, Hashable {
    public var id: String
    public var name: String
    public var fields: [FieldDefinition]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, name: String, fields: [FieldDefinition]) {
        self.id = id
        self.name = name
        self.fields = fields
    }

    

    
}

#if compiler(>=6)
extension Database: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDatabase: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Database {
        return
            try Database(
                id: FfiConverterString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                fields: FfiConverterSequenceTypeFieldDefinition.read(from: &buf)
        )
    }

    public static func write(_ value: Database, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterSequenceTypeFieldDefinition.write(value.fields, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDatabase_lift(_ buf: RustBuffer) throws -> Database {
    return try FfiConverterTypeDatabase.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDatabase_lower(_ value: Database) -> RustBuffer {
    return FfiConverterTypeDatabase.lower(value)
}


public struct FieldDefinition: Equatable, Hashable {
    public var id: String
    public var name: String
    public var kind: FieldKind
    public var ordering: Int32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, name: String, kind: FieldKind, ordering: Int32) {
        self.id = id
        self.name = name
        self.kind = kind
        self.ordering = ordering
    }

    

    
}

#if compiler(>=6)
extension FieldDefinition: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFieldDefinition: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FieldDefinition {
        return
            try FieldDefinition(
                id: FfiConverterString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                kind: FfiConverterTypeFieldKind.read(from: &buf), 
                ordering: FfiConverterInt32.read(from: &buf)
        )
    }

    public static func write(_ value: FieldDefinition, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterTypeFieldKind.write(value.kind, into: &buf)
        FfiConverterInt32.write(value.ordering, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFieldDefinition_lift(_ buf: RustBuffer) throws -> FieldDefinition {
    return try FfiConverterTypeFieldDefinition.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFieldDefinition_lower(_ value: FieldDefinition) -> RustBuffer {
    return FfiConverterTypeFieldDefinition.lower(value)
}


public struct Record: Equatable, Hashable {
    public var link: String
    public var databaseId: String
    public var values: [String: Value]
    /**
     * RFC3339.
     */
    public var createdAt: String
    /**
     * RFC3339.
     */
    public var updatedAt: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(link: String, databaseId: String, values: [String: Value], 
        /**
         * RFC3339.
         */createdAt: String, 
        /**
         * RFC3339.
         */updatedAt: String) {
        self.link = link
        self.databaseId = databaseId
        self.values = values
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    

    
}

#if compiler(>=6)
extension Record: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRecord: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Record {
        return
            try Record(
                link: FfiConverterString.read(from: &buf), 
                databaseId: FfiConverterString.read(from: &buf), 
                values: FfiConverterDictionaryStringTypeValue.read(from: &buf), 
                createdAt: FfiConverterString.read(from: &buf), 
                updatedAt: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: Record, into buf: inout [UInt8]) {
        FfiConverterString.write(value.link, into: &buf)
        FfiConverterString.write(value.databaseId, into: &buf)
        FfiConverterDictionaryStringTypeValue.write(value.values, into: &buf)
        FfiConverterString.write(value.createdAt, into: &buf)
        FfiConverterString.write(value.updatedAt, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRecord_lift(_ buf: RustBuffer) throws -> Record {
    return try FfiConverterTypeRecord.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRecord_lower(_ value: Record) -> RustBuffer {
    return FfiConverterTypeRecord.lower(value)
}


public struct Reference: Equatable, Hashable {
    public var id: String
    public var sourceLink: String
    public var sourceField: String
    public var targetLink: String
    public var targetField: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, sourceLink: String, sourceField: String, targetLink: String, targetField: String) {
        self.id = id
        self.sourceLink = sourceLink
        self.sourceField = sourceField
        self.targetLink = targetLink
        self.targetField = targetField
    }

    

    
}

#if compiler(>=6)
extension Reference: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeReference: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Reference {
        return
            try Reference(
                id: FfiConverterString.read(from: &buf), 
                sourceLink: FfiConverterString.read(from: &buf), 
                sourceField: FfiConverterString.read(from: &buf), 
                targetLink: FfiConverterString.read(from: &buf), 
                targetField: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: Reference, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.sourceLink, into: &buf)
        FfiConverterString.write(value.sourceField, into: &buf)
        FfiConverterString.write(value.targetLink, into: &buf)
        FfiConverterString.write(value.targetField, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeReference_lift(_ buf: RustBuffer) throws -> Reference {
    return try FfiConverterTypeReference.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeReference_lower(_ value: Reference) -> RustBuffer {
    return FfiConverterTypeReference.lower(value)
}


/**
 * Every link whose value was cleared by a `retypeField` call because it
 * wasn't representable under the new kind — never silent data loss, per
 * Architecture.md §7.
 */
public struct RetypeReport: Equatable, Hashable {
    public var clearedLinks: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(clearedLinks: [String]) {
        self.clearedLinks = clearedLinks
    }

    

    
}

#if compiler(>=6)
extension RetypeReport: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRetypeReport: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RetypeReport {
        return
            try RetypeReport(
                clearedLinks: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: RetypeReport, into buf: inout [UInt8]) {
        FfiConverterSequenceString.write(value.clearedLinks, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRetypeReport_lift(_ buf: RustBuffer) throws -> RetypeReport {
    return try FfiConverterTypeRetypeReport.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRetypeReport_lower(_ value: RetypeReport) -> RustBuffer {
    return FfiConverterTypeRetypeReport.lower(value)
}


public struct SelectionOption: Equatable, Hashable {
    public var name: String
    public var color: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, color: String) {
        self.name = name
        self.color = color
    }

    

    
}

#if compiler(>=6)
extension SelectionOption: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSelectionOption: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SelectionOption {
        return
            try SelectionOption(
                name: FfiConverterString.read(from: &buf), 
                color: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: SelectionOption, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.color, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSelectionOption_lift(_ buf: RustBuffer) throws -> SelectionOption {
    return try FfiConverterTypeSelectionOption.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSelectionOption_lower(_ value: SelectionOption) -> RustBuffer {
    return FfiConverterTypeSelectionOption.lower(value)
}


public 
enum DataLineError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case DatabaseNotFound(id: String
    )
    case FieldNotFound(id: String
    )
    case RecordNotFound(id: String
    )
    case ReferenceNotFound(id: String
    )
    case BlobNotFound(hash: String
    )
    case ValueKindMismatch(field: String, expected: String
    )
    case UnsupportedFieldKindForValue(field: String, kind: String
    )
    case ReferenceTargetDatabaseMismatch(field: String, expected: String, actual: String
    )
    case ReferenceFieldRetypeNotSupported(field: String
    )
    case Storage(message: String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension DataLineError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDataLineError: FfiConverterRustBuffer {
    typealias SwiftType = DataLineError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DataLineError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .DatabaseNotFound(
            id: try FfiConverterString.read(from: &buf)
            )
        case 2: return .FieldNotFound(
            id: try FfiConverterString.read(from: &buf)
            )
        case 3: return .RecordNotFound(
            id: try FfiConverterString.read(from: &buf)
            )
        case 4: return .ReferenceNotFound(
            id: try FfiConverterString.read(from: &buf)
            )
        case 5: return .BlobNotFound(
            hash: try FfiConverterString.read(from: &buf)
            )
        case 6: return .ValueKindMismatch(
            field: try FfiConverterString.read(from: &buf), 
            expected: try FfiConverterString.read(from: &buf)
            )
        case 7: return .UnsupportedFieldKindForValue(
            field: try FfiConverterString.read(from: &buf), 
            kind: try FfiConverterString.read(from: &buf)
            )
        case 8: return .ReferenceTargetDatabaseMismatch(
            field: try FfiConverterString.read(from: &buf), 
            expected: try FfiConverterString.read(from: &buf), 
            actual: try FfiConverterString.read(from: &buf)
            )
        case 9: return .ReferenceFieldRetypeNotSupported(
            field: try FfiConverterString.read(from: &buf)
            )
        case 10: return .Storage(
            message: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: DataLineError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .DatabaseNotFound(id):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(id, into: &buf)
            
        
        case let .FieldNotFound(id):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(id, into: &buf)
            
        
        case let .RecordNotFound(id):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(id, into: &buf)
            
        
        case let .ReferenceNotFound(id):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(id, into: &buf)
            
        
        case let .BlobNotFound(hash):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(hash, into: &buf)
            
        
        case let .ValueKindMismatch(field,expected):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(field, into: &buf)
            FfiConverterString.write(expected, into: &buf)
            
        
        case let .UnsupportedFieldKindForValue(field,kind):
            writeInt(&buf, Int32(7))
            FfiConverterString.write(field, into: &buf)
            FfiConverterString.write(kind, into: &buf)
            
        
        case let .ReferenceTargetDatabaseMismatch(field,expected,actual):
            writeInt(&buf, Int32(8))
            FfiConverterString.write(field, into: &buf)
            FfiConverterString.write(expected, into: &buf)
            FfiConverterString.write(actual, into: &buf)
            
        
        case let .ReferenceFieldRetypeNotSupported(field):
            writeInt(&buf, Int32(9))
            FfiConverterString.write(field, into: &buf)
            
        
        case let .Storage(message):
            writeInt(&buf, Int32(10))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDataLineError_lift(_ buf: RustBuffer) throws -> DataLineError {
    return try FfiConverterTypeDataLineError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDataLineError_lower(_ value: DataLineError) -> RustBuffer {
    return FfiConverterTypeDataLineError.lower(value)
}



public enum FieldKind: Equatable, Hashable {
    
    case text
    case number
    case boolean
    case selection(multi: Bool, options: [SelectionOption]
    )
    case date
    /**
     * `target_database` is a database id string. `paired_field` is ignored
     * on the way in — `dataline-core::SchemaRegistry::add_field` always
     * establishes pairing itself, the same way it ignores a caller-supplied
     * value for this today (see that method's tests).
     */
    case reference(targetDatabase: String, pairedField: String?
    )
    case blob





}

#if compiler(>=6)
extension FieldKind: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFieldKind: FfiConverterRustBuffer {
    typealias SwiftType = FieldKind

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FieldKind {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .text
        
        case 2: return .number
        
        case 3: return .boolean
        
        case 4: return .selection(multi: try FfiConverterBool.read(from: &buf), options: try FfiConverterSequenceTypeSelectionOption.read(from: &buf)
        )
        
        case 5: return .date
        
        case 6: return .reference(targetDatabase: try FfiConverterString.read(from: &buf), pairedField: try FfiConverterOptionString.read(from: &buf)
        )
        
        case 7: return .blob
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FieldKind, into buf: inout [UInt8]) {
        switch value {
        
        
        case .text:
            writeInt(&buf, Int32(1))
        
        
        case .number:
            writeInt(&buf, Int32(2))
        
        
        case .boolean:
            writeInt(&buf, Int32(3))
        
        
        case let .selection(multi,options):
            writeInt(&buf, Int32(4))
            FfiConverterBool.write(multi, into: &buf)
            FfiConverterSequenceTypeSelectionOption.write(options, into: &buf)
            
        
        case .date:
            writeInt(&buf, Int32(5))
        
        
        case let .reference(targetDatabase,pairedField):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(targetDatabase, into: &buf)
            FfiConverterOptionString.write(pairedField, into: &buf)
            
        
        case .blob:
            writeInt(&buf, Int32(7))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFieldKind_lift(_ buf: RustBuffer) throws -> FieldKind {
    return try FfiConverterTypeFieldKind.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFieldKind_lower(_ value: FieldKind) -> RustBuffer {
    return FfiConverterTypeFieldKind.lower(value)
}




public enum Value: Equatable, Hashable {
    
    case text(String
    )
    case number(Double
    )
    case boolean(Bool
    )
    case selection([String]
    )
    /**
     * `"YYYY-MM-DD"`.
     */
    case date(String
    )
    /**
     * Links, as id strings.
     */
    case reference([String]
    )
    /**
     * A blob's content hash, as returned by `Store::write_blob`.
     */
    case blob(String
    )
    case empty





}

#if compiler(>=6)
extension Value: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeValue: FfiConverterRustBuffer {
    typealias SwiftType = Value

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Value {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .text(try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .number(try FfiConverterDouble.read(from: &buf)
        )
        
        case 3: return .boolean(try FfiConverterBool.read(from: &buf)
        )
        
        case 4: return .selection(try FfiConverterSequenceString.read(from: &buf)
        )
        
        case 5: return .date(try FfiConverterString.read(from: &buf)
        )
        
        case 6: return .reference(try FfiConverterSequenceString.read(from: &buf)
        )
        
        case 7: return .blob(try FfiConverterString.read(from: &buf)
        )
        
        case 8: return .empty
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Value, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .text(v1):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .number(v1):
            writeInt(&buf, Int32(2))
            FfiConverterDouble.write(v1, into: &buf)
            
        
        case let .boolean(v1):
            writeInt(&buf, Int32(3))
            FfiConverterBool.write(v1, into: &buf)
            
        
        case let .selection(v1):
            writeInt(&buf, Int32(4))
            FfiConverterSequenceString.write(v1, into: &buf)
            
        
        case let .date(v1):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .reference(v1):
            writeInt(&buf, Int32(6))
            FfiConverterSequenceString.write(v1, into: &buf)
            
        
        case let .blob(v1):
            writeInt(&buf, Int32(7))
            FfiConverterString.write(v1, into: &buf)
            
        
        case .empty:
            writeInt(&buf, Int32(8))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeValue_lift(_ buf: RustBuffer) throws -> Value {
    return try FfiConverterTypeValue.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeValue_lower(_ value: Value) -> RustBuffer {
    return FfiConverterTypeValue.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeDatabase: FfiConverterRustBuffer {
    typealias SwiftType = [Database]

    public static func write(_ value: [Database], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeDatabase.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Database] {
        let len: Int32 = try readInt(&buf)
        var seq = [Database]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeDatabase.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFieldDefinition: FfiConverterRustBuffer {
    typealias SwiftType = [FieldDefinition]

    public static func write(_ value: [FieldDefinition], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFieldDefinition.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FieldDefinition] {
        let len: Int32 = try readInt(&buf)
        var seq = [FieldDefinition]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFieldDefinition.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeRecord: FfiConverterRustBuffer {
    typealias SwiftType = [Record]

    public static func write(_ value: [Record], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeRecord.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Record] {
        let len: Int32 = try readInt(&buf)
        var seq = [Record]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeRecord.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeReference: FfiConverterRustBuffer {
    typealias SwiftType = [Reference]

    public static func write(_ value: [Reference], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeReference.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Reference] {
        let len: Int32 = try readInt(&buf)
        var seq = [Reference]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeReference.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeSelectionOption: FfiConverterRustBuffer {
    typealias SwiftType = [SelectionOption]

    public static func write(_ value: [SelectionOption], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSelectionOption.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [SelectionOption] {
        let len: Int32 = try readInt(&buf)
        var seq = [SelectionOption]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeSelectionOption.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDictionaryStringTypeValue: FfiConverterRustBuffer {
    public static func write(_ value: [String: Value], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for (key, value) in value {
            FfiConverterString.write(key, into: &buf)
            FfiConverterTypeValue.write(value, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String: Value] {
        let len: Int32 = try readInt(&buf)
        var dict = [String: Value]()
        dict.reserveCapacity(Int(len))
        for _ in 0..<len {
            let key = try FfiConverterString.read(from: &buf)
            let value = try FfiConverterTypeValue.read(from: &buf)
            dict[key] = value
        }
        return dict
    }
}
/**
 * This crate's version (`dataline-ffi`'s own semver, which tracks
 * `dataline-core`'s). Doesn't need a `Store` open — pure identity, callable
 * before touching any store file. Architecture.md §8 calls this out as
 * something Line's future plugin contract will want for free; it costs
 * nothing to expose today even with no Line to hand it to yet.
 */
public func datalineVersion() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_dataline_ffi_fn_func_dataline_version(uniffiCallStatus
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_dataline_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_dataline_ffi_checksum_func_dataline_version() != 65328) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dataline_ffi_checksum_method_store_add_field() != 64269) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dataline_ffi_checksum_method_store_create_database() != 46173) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dataline_ffi_checksum_method_store_create_record() != 49208) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dataline_ffi_checksum_method_store_create_reference() != 13465) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dataline_ffi_checksum_method_store_delete_record() != 31450) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dataline_ffi_checksum_method_store_delete_reference() != 21083) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dataline_ffi_checksum_method_store_duplicate_database_schema() != 26989) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dataline_ffi_checksum_method_store_find_by_value() != 35961) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dataline_ffi_checksum_method_store_get_database() != 150) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dataline_ffi_checksum_method_store_get_record() != 7466) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dataline_ffi_checksum_method_store_list_databases() != 32777) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dataline_ffi_checksum_method_store_list_records() != 11310) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dataline_ffi_checksum_method_store_list_references() != 41151) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dataline_ffi_checksum_method_store_read_blob() != 45261) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dataline_ffi_checksum_method_store_related_records() != 59272) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dataline_ffi_checksum_method_store_remove_field() != 19406) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dataline_ffi_checksum_method_store_rename_field() != 55949) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dataline_ffi_checksum_method_store_retype_field() != 50448) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dataline_ffi_checksum_method_store_search_text() != 31675) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dataline_ffi_checksum_method_store_set_value() != 24026) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dataline_ffi_checksum_method_store_write_blob() != 55483) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dataline_ffi_checksum_constructor_store_open() != 48682) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureDatalineFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all